ERROR:root:Error while makin moves:
Traceback (most recent call last):
  File "BotVerbRun1.py", line 37, in run
    moves = self.interpret(line)
  File "BotVerbRun1.py", line 50, in interpret
    return self._planner.makeMove()
  File "C:\Users\agiera\Documents\UMass\cs383\TETRISAI\TETbot\Bot\Planner.py", line 20, in makeMove
    return self._strategy.choose()
  File "C:\Users\agiera\Documents\UMass\cs383\TETRISAI\TETbot\Bot\Strategies\SearchDeepQStrategy.py", line 146, in choose
    return self.move_set[move]
UnboundLocalError: local variable 'move' referenced before assignment
ERROR:root:Error while makin moves:
Traceback (most recent call last):
  File "BotVerbRun1.py", line 37, in run
    moves = self.interpret(line)
  File "BotVerbRun1.py", line 50, in interpret
    return self._planner.makeMove()
  File "C:\Users\agiera\Documents\UMass\cs383\TETRISAI\TETbot\Bot\Planner.py", line 20, in makeMove
    return self._strategy.choose()
  File "C:\Users\agiera\Documents\UMass\cs383\TETRISAI\TETbot\Bot\Strategies\SearchDeepQStrategy.py", line 146, in choose
    return self.move_set[move]
UnboundLocalError: local variable 'move' referenced before assignment
ed before assignment
